server:
  http:
    addr: 0.0.0.0:8998
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8999
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:8086)/recruit?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:8089
    db: 8
    passWord: "123456"
    read_timeout: 2s
    write_timeout: 2s

